# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cultured Systems
tagline:          'Everyday life and the sociability of code'
description:      ''
url:              http://www.cultured.systems/
baseurl:          /

author:
  name:           'Tim Fisken'
  url:            http://www.cultured.systems/

paginate:         5

  

